Update golang and small fix
reconness/reconness-agents pull request #11
Opened 2021-02-20 01:23 UTC by hiddengearz

Updated Golang and resolved the installation of golang universal warpper. One of the imports required [Golang modules](https://github.com/golang/go/wiki/Modules) to be enabled.

2021-02-21 05:49 UTC, gorums requested changes

2021-02-21 05:49 UTC, gorums commented on Dockerfile
> +RUN /root/go/bin/reconness-universal-wrapper setup -u bossman -p e5AtyDDJbY3eAv1z -s https://recon.hiddengearz.com
-u <reconness username> -p <reconness password> -s <reconness.mydomain.com>

2021-02-21 06:07 UTC, hiddengearz commented on Dockerfile
> +RUN /root/go/bin/reconness-universal-wrapper setup -u bossman -p e5AtyDDJbY3eAv1z -s https://recon.hiddengearz.com
and that my friends is why you use environment variables... So you don't have to go reinstall a VM.

2021-02-27 19:01 UTC, gorums commented
I'm going to close this PR to avoid put the credentials as a commit. I put the change that you provided and is working fine. Thx again

2021-02-27 19:01 UTC, closed without merging